language: android

jdk:
  - oraclejdk8

branches:
  only:
   - master

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-25.0.1
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository

addons:
  ssh_known_hosts: "52.57.200.243"

after_script:
 - cd android
 - cd app
 - cd build
 - ls -l -a
 - eval "$(ssh-agent -s)"
 - chmod 400 /home/travis/build/ramimahfoud/amos-ss17-proj7/keyssh
 - ssh-add /home/travis/build/ramimahfoud/amos-ss17-proj7/keyssh
 - scp -rp -i /home/travis/build/ramimahfoud/amos-ss17-proj7/keyssh /home/travis/build/ramimahfoud/amos-ss17-proj7/server/build/libs/server-1.0-SNAPSHOT.war ubuntu@52.57.200.243:/home/ubuntu/glassfish4/glassfish/domains/domain1/autodeploy


