language: java

jdk:
  - oraclejdk8

before_script:
 - pwd

addons:
  ssh_known_hosts: <deploy-host>

after_script:
 - cd server
 - cd build
 - cd libs
 - ls -l
 - ls -a

 before_deploy:
 - eval "$(ssh-agent -s)"
 - chmod 600 /home/travis/build/ramimahfoud/amos-ss17-proj7/keyssh
 - ssh-add /home/travis/build/ramimahfoud/amos-ss17-proj7/keyssh
 - ssh ubuntu@52.57.200.243




