language: java

jdk:
  - oraclejdk8

before_install:
  - gradle -b wrapper.gradle wrapper
  - cd /home/travis/build/BankingBoys/amos-ss17-proj7
  - echo -e $sshcert > keyssh

install:
  - cd /home/travis/build/BankingBoys/
  - sudo apt install unzip   
  - if [ ! -f ./tools/android ]; then wget https://dl.google.com/android/repository/tools_r25.2.3-linux.zip ; fi   
  - if [ ! -f ./tools/android ]; then unzip tools_r25.2.3-linux.zip ; fi   
  - ls
  - export ANDROID_HOME=/home/travis/build/BankingBoys/
  - export PATH=$PATH:/home/travis/build/BankingBoys/ools
  - export PATH=$PATH://home/travis/build/BankingBoys/platform-tools
  - cd tools


  - if [ ! -d ./../build-tools/25.0.5 ]; then echo y | ./android update sdk --no-ui --all --filter "build-tools-25.0.5" ; fi   
  - if [ ! -d ./../extras ]; then echo y | ./android update sdk --no-ui --all --filter "tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository" ; fi   
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - cd /home/travis/build/BankingBoys/amos-ss17-proj7/
addons:
  ssh_known_hosts: "13.58.27.176"

after_script:
 - ./gradlew server:uploadArchives
 - cd android
 - cd app
 - cd build
 - ls -l
 - eval "$(ssh-agent -s)"
 - chmod 400 /home/travis/build/BankingBoys/amos-ss17-proj7/keyssh
 - ssh-add /home/travis/build/BankingBoys/amos-ss17-proj7/keyssh
 - scp -rp -i /home/travis/build/BankingBoys/amos-ss17-proj7/keyssh /home/travis/build/BankingBoys/amos-ss17-proj7/server/compiled/server-1.0-SNAPSHOT.war ubuntu@13.58.27.176:/home/ubuntu/
 - ssh -i /home/travis/build/BankingBoys/amos-ss17-proj7/keyssh ubuntu@13.58.27.176 "/home/ubuntu/pay/payara41/bin/asadmin --user admin --passwordfile ~/payPW redeploy --name server-1.0-SNAPSHOT server-1.0-SNAPSHOT.war"
 -  cd /home/travis/build/BankingBoys/amos-ss17-proj7/
 - ./gradlew android:app:assemble
 - cd android/app/build/outputs/apk
 - curl -F "status=2" -F "notify=1" -F "notes=auto deploy." -F "notes_type=0" -F "ipa=@app-debug.apk" -H "X-HockeyAppToken: $hockeyapptoken" https://rink.hockeyapp.net/api/2/apps/4adac746746644d8ad6c94939495c7ff//app_versions/upload


notifications:
    slack: amosteam5:WF2UyrAWwmuoSgjjtqPo8O1N

after_success:
 - ./gradlew jacocoTestReport coveralls
 - bash <(curl -s https://codecov.io/bash) -t cf0de81b-58db-4ef3-ae21-7e98da69c415

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/
    - /home/travis/build/BankingBoys/tools/
    - /home/travis/build/BankingBoys/build-tools/


