package de.fau.amos.virtualledger.server.banking.adorsys.api.bankAccountEndpoint;

import de.fau.amos.virtualledger.server.banking.adorsys.api.bankAccessEndpoint.DummyBankAccessBankingModelEntity;
import de.fau.amos.virtualledger.server.banking.model.BankAccountBalanceBankingModel;
import de.fau.amos.virtualledger.server.banking.model.BankAccountBankingModel;
import de.fau.amos.virtualledger.server.banking.model.BookingModel;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "dummies_bank_account_banking_models")
public class DummyBankAccountBankingModelEntity {

    @ManyToOne
    private DummyBankAccessBankingModelEntity bankAccess = null;

    @Transient
    private BankAccountBalanceBankingModel bankAccountBalance = null;
    @Transient
    private List<BookingModel> bookingsList = new ArrayList<>();

    private String bicHbciAccount = null;
    private String blzHbciAccount = null;
    private String countryHbciAccount = null;
    private String currencyHbciAccount = null;
    private String ibanHbciAccount = null;

    /**
     * The id of a bank account generated by dummy is unique!
     * This would not apply to real bank accounts!
     */
    @Id
    private String id = null;

    private String nameHbciAccount = null;
    private String numberHbciAccount = null;
    private String typeHbciAccount = null;

    public DummyBankAccountBankingModelEntity() {
    }

    public DummyBankAccountBankingModelEntity(BankAccountBankingModel bankAccountBankingModel, DummyBankAccessBankingModelEntity dummyBankAccessBankingModelEntity) {
        bankAccess = dummyBankAccessBankingModelEntity;
        bicHbciAccount = bankAccountBankingModel.getBicHbciAccount();
        blzHbciAccount = bankAccountBankingModel.getBlzHbciAccount();
        countryHbciAccount = bankAccountBankingModel.getCountryHbciAccount();
        currencyHbciAccount = bankAccountBankingModel.getCurrencyHbciAccount();
        ibanHbciAccount = bankAccountBankingModel.getIbanHbciAccount();
        id = bankAccountBankingModel.getId();
        nameHbciAccount = bankAccountBankingModel.getNameHbciAccount();
        numberHbciAccount = bankAccountBankingModel.getNumberHbciAccount();
        typeHbciAccount = bankAccountBankingModel.getTypeHbciAccount();
    }


    public DummyBankAccessBankingModelEntity getBankAccess() {
        return bankAccess;
    }

    public void setBankAccess(DummyBankAccessBankingModelEntity bankAccess) {
        this.bankAccess = bankAccess;
    }

    public String getBicHbciAccount() {
        return bicHbciAccount;
    }

    public void setBicHbciAccount(String bicHbciAccount) {
        this.bicHbciAccount = bicHbciAccount;
    }

    public String getBlzHbciAccount() {
        return blzHbciAccount;
    }

    public void setBlzHbciAccount(String blzHbciAccount) {
        this.blzHbciAccount = blzHbciAccount;
    }

    public String getCountryHbciAccount() {
        return countryHbciAccount;
    }

    public void setCountryHbciAccount(String countryHbciAccount) {
        this.countryHbciAccount = countryHbciAccount;
    }

    public String getCurrencyHbciAccount() {
        return currencyHbciAccount;
    }

    public void setCurrencyHbciAccount(String currencyHbciAccount) {
        this.currencyHbciAccount = currencyHbciAccount;
    }

    public String getIbanHbciAccount() {
        return ibanHbciAccount;
    }

    public void setIbanHbciAccount(String ibanHbciAccount) {
        this.ibanHbciAccount = ibanHbciAccount;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNameHbciAccount() {
        return nameHbciAccount;
    }

    public void setNameHbciAccount(String nameHbciAccount) {
        this.nameHbciAccount = nameHbciAccount;
    }

    public String getNumberHbciAccount() {
        return numberHbciAccount;
    }

    public void setNumberHbciAccount(String numberHbciAccount) {
        this.numberHbciAccount = numberHbciAccount;
    }

    public String getTypeHbciAccount() {
        return typeHbciAccount;
    }

    public void setTypeHbciAccount(String typeHbciAccount) {
        this.typeHbciAccount = typeHbciAccount;
    }

    public BankAccountBalanceBankingModel getBankAccountBalance() {
        return bankAccountBalance;
    }

    public void setBankAccountBalance(BankAccountBalanceBankingModel bankAccountBalance) {
        this.bankAccountBalance = bankAccountBalance;
    }

    public List<BookingModel> getBookingsList() {
        return bookingsList;
    }

    public void setBookingsList(List<BookingModel> bookingsList) {
        this.bookingsList = bookingsList;
    }

    public BankAccountBankingModel transformIntoBankAccountBankingModel() {
        BankAccountBankingModel bankAccountBankingModel = new BankAccountBankingModel();

        BankAccountBalanceBankingModel bankAccountBalanceBankingModel = new BankAccountBalanceBankingModel();
        bankAccountBalanceBankingModel.setReadyHbciBalance(bankAccountBalance.getReadyHbciBalance());
        bankAccountBalanceBankingModel.setAvailableHbciBalance(bankAccountBalance.getAvailableHbciBalance());
        bankAccountBankingModel.setBankAccountBalance(bankAccountBalanceBankingModel);

        bankAccountBankingModel.setBicHbciAccount(bicHbciAccount);
        bankAccountBankingModel.setBlzHbciAccount(blzHbciAccount);
        bankAccountBankingModel.setCountryHbciAccount(countryHbciAccount);
        bankAccountBankingModel.setCurrencyHbciAccount(currencyHbciAccount);
        bankAccountBankingModel.setIbanHbciAccount(ibanHbciAccount);
        bankAccountBankingModel.setId(id);
        bankAccountBankingModel.setNameHbciAccount(nameHbciAccount);
        bankAccountBankingModel.setNumberHbciAccount(numberHbciAccount);
        bankAccountBankingModel.setTypeHbciAccount(typeHbciAccount);
        bankAccountBankingModel.setBankAccessId(bankAccess.getId());
        return bankAccountBankingModel;
    }
}
